quadrantChart
    title "Efficiency and Robustness of Code"
    x-axis "Low Efficiency" --> "High Efficiency"
    y-axis "Low Robustness" --> "High Robustness"
    quadrant-1 "We should expand"
    quadrant-2 "Need to promote"
    quadrant-3 "Re-evaluate"
    quadrant-4 "May be improved"
    "Product A": [0.7, 0.3]
    "Product B": [0.3, 0.7]
    "Product C": [0.6, 0.6]
    "Our Target Product": [0.8, 0.8]