quadrantChart
    title "Efficiency and visual appeal of converters"
    x-axis "Low Efficiency" --> "High Efficiency"
    y-axis "Low Visual Appeal" --> "High Visual Appeal"
    quadrant-1 "We should expand"
    quadrant-2 "Need to promote"
    quadrant-3 "Re-evaluate"
    quadrant-4 "May be improved"
    "Converter A": [0.7, 0.3]
    "Converter B": [0.5, 0.7]
    "Converter C": [0.6, 0.4]
    "Our Target Product": [0.9, 0.9]